name: Python Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system packages for compiling extensions
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake g++ pkg-config

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pybind11
        pip install pytest	
        pip install . --no-deps

    - name: Run tests
      env:
        PYTHONPATH: .
      run: pytest
